export interface JobOpeningInterface{
    // "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "jobId": "string",
  "jobTitle": "string",
  "accountId": "string",
  "projectId": "string",
  "skillSet": "string",
  "yearOfExp": "string",
  "qualification": "string",
  "jobDescription": "string",
  "noOfPositions": "number",
  "budget": "string",
  "location": "string",
  "account":"string",
  "project":"string",
  "totalcandidate":"string",
"hired":"string",
"status":"string",
"screening":"string",
"L1":"string",
"L2":"string",
"Managerial":"string",
"HR":"string",

}