export interface JobOpeningInterface{
    // "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "jobId": string,
  id:string,
  "jobTitle": string,
  "accountId": string,
  "accountName":string,
  "projectName":string,
  "projectId": string,
  "skillSet": string,
  "yearOfExp": string,
  "qualification": string,
  "jobDescription": string,
  "noOfPositions": number,
  "budget": string,
  "location": string,
  "account":string,
  "project":string, 
"hired":string,
"status":string,
"totalApplied":string,
"screenings":string,
"l1s":string,
"l2s":string,
"managerials":string,
"hr":string,
"offers":string,
"onboarded":string,
}